[tasks.create-app-ui]
id = "create-app-ui"
message = "create app ui"
status = "pending"
dependencies = []
created = "2026-01-10T09:43:34.876096"
started = ""
completed = ""
cancelled = false

[tasks.finish-poc]
id = "finish-poc"
message = "finish poc"
status = "pending"
dependencies = [
    "create-app-ui",
]
created = "2026-01-10T09:46:56.972509"
started = ""
completed = ""
cancelled = false
